// Auto-generated list of bundled fonts
export interface FontDef { family: string; category: 'sans' | 'serif' | 'display' | 'script' | 'mono'; bold: boolean; italic: boolean }
export const BUNDLED_FONTS: FontDef[] = [
  { family: 'Inter', category: 'sans', bold: true, italic: true },
  { family: 'Montserrat', category: 'sans', bold: true, italic: true },
  { family: 'Poppins', category: 'sans', bold: true, italic: true },
  { family: 'Playfair Display', category: 'serif', bold: true, italic: true },
  { family: 'Roboto', category: 'sans', bold: true, italic: true },
  { family: 'Open Sans', category: 'sans', bold: true, italic: true },
  { family: 'Lato', category: 'sans', bold: true, italic: true },
  { family: 'Oswald', category: 'display', bold: true, italic: false },
  { family: 'Raleway', category: 'sans', bold: true, italic: true },
  { family: 'Bebas Neue', category: 'display', bold: false, italic: false },
  { family: 'Pacifico', category: 'script', bold: false, italic: false },
  { family: 'Lobster', category: 'script', bold: false, italic: false },
  { family: 'Merriweather', category: 'serif', bold: true, italic: true },
  { family: 'Dancing Script', category: 'script', bold: true, italic: false },
  { family: 'Anton', category: 'display', bold: false, italic: false },
  { family: 'Abril Fatface', category: 'serif', bold: false, italic: false },
  { family: 'Caveat', category: 'script', bold: true, italic: false },
  { family: 'Space Grotesk', category: 'sans', bold: true, italic: false },
  { family: 'DM Serif Display', category: 'serif', bold: false, italic: true },
  { family: 'Archivo Black', category: 'display', bold: false, italic: false },
  { family: 'Bungee', category: 'display', bold: false, italic: false },
  { family: 'Permanent Marker', category: 'script', bold: false, italic: false },
  { family: 'Great Vibes', category: 'script', bold: false, italic: false },
  { family: 'Quicksand', category: 'sans', bold: true, italic: false },
  { family: 'Nunito', category: 'sans', bold: true, italic: true },
  { family: 'Josefin Sans', category: 'sans', bold: true, italic: true },
  { family: 'Cormorant Garamond', category: 'serif', bold: true, italic: true },
  { family: 'Source Code Pro', category: 'mono', bold: true, italic: true },
  { family: 'Righteous', category: 'display', bold: false, italic: false },
  { family: 'Alfa Slab One', category: 'display', bold: false, italic: false },
  { family: 'Satisfy', category: 'script', bold: false, italic: false },
  { family: 'Shadows Into Light', category: 'script', bold: false, italic: false },
  { family: 'Fredoka', category: 'display', bold: true, italic: false },
  { family: 'Libre Baskerville', category: 'serif', bold: true, italic: true },
  { family: 'Lora', category: 'serif', bold: true, italic: true },
  { family: 'Bitter', category: 'serif', bold: true, italic: true },
  { family: 'Cinzel', category: 'serif', bold: true, italic: false },
  { family: 'Comfortaa', category: 'display', bold: true, italic: false },
  { family: 'Amatic SC', category: 'script', bold: true, italic: false },
  { family: 'Kalam', category: 'script', bold: true, italic: false },
];
