// Curated sticker/emoji set. Rendered with the Windows colour emoji font ("Segoe UI Emoji").
export interface EmojiDef {
  char: string;
  name: string;
  keys: string;
}

const RAW: [string, string, string][] = [
  // smileys
  ['😀', 'Grinning face', 'smile happy face joy'],
  ['😂', 'Tears of joy', 'laugh lol funny face'],
  ['🥹', 'Holding back tears', 'grateful touched face'],
  ['😊', 'Smiling face', 'blush happy face'],
  ['😍', 'Heart eyes', 'love crush face'],
  ['🥰', 'Smiling with hearts', 'love adore face'],
  ['😎', 'Cool face', 'sunglasses cool face'],
  ['🤩', 'Star struck', 'wow excited face'],
  ['😉', 'Winking face', 'wink flirt face'],
  ['🤔', 'Thinking face', 'hmm think question face'],
  ['😴', 'Sleeping face', 'sleep tired zzz face'],
  ['😮', 'Surprised face', 'wow shock face'],
  ['😢', 'Crying face', 'sad tear face'],
  ['😡', 'Angry face', 'mad rage face'],
  ['🥳', 'Party face', 'celebrate birthday party face'],
  ['😇', 'Angel face', 'halo innocent face'],
  ['🤗', 'Hugging face', 'hug welcome face'],
  ['🙃', 'Upside-down face', 'silly sarcasm face'],
  ['🤯', 'Mind blown', 'shock wow explode face'],
  ['😱', 'Screaming face', 'fear scared halloween face'],
  ['🤖', 'Robot', 'robot tech ai bot'],
  ['👻', 'Ghost', 'ghost halloween spooky'],
  ['💀', 'Skull', 'skull dead halloween'],
  ['💩', 'Pile of poo', 'poop funny'],
  // hands & people
  ['👍', 'Thumbs up', 'like yes ok approve hand'],
  ['👎', 'Thumbs down', 'dislike no hand'],
  ['👏', 'Clapping hands', 'clap applause bravo hand'],
  ['🙌', 'Raising hands', 'hooray celebrate hand'],
  ['🙏', 'Folded hands', 'thanks please pray hand'],
  ['👋', 'Waving hand', 'hello hi bye wave hand'],
  ['✌️', 'Victory hand', 'peace hand'],
  ['🤞', 'Crossed fingers', 'luck hope hand'],
  ['👉', 'Pointing right', 'point right hand'],
  ['👇', 'Pointing down', 'point down hand'],
  ['💪', 'Flexed biceps', 'strong muscle gym fitness'],
  ['👀', 'Eyes', 'look see watch'],
  ['🧠', 'Brain', 'smart think mind'],
  // hearts & symbols
  ['❤️', 'Red heart', 'love heart red valentine'],
  ['🧡', 'Orange heart', 'love heart orange'],
  ['💛', 'Yellow heart', 'love heart yellow'],
  ['💚', 'Green heart', 'love heart green'],
  ['💙', 'Blue heart', 'love heart blue'],
  ['💜', 'Purple heart', 'love heart purple'],
  ['🖤', 'Black heart', 'love heart black'],
  ['💖', 'Sparkling heart', 'love heart sparkle'],
  ['💔', 'Broken heart', 'sad heartbreak'],
  ['💯', 'Hundred points', '100 perfect score'],
  ['✅', 'Check mark', 'done yes tick check'],
  ['❌', 'Cross mark', 'no wrong x cross'],
  ['⚠️', 'Warning', 'warning caution alert'],
  ['❗', 'Exclamation mark', 'important alert'],
  ['❓', 'Question mark', 'question help'],
  ['💬', 'Speech balloon', 'chat comment message talk'],
  ['💡', 'Light bulb', 'idea tip light'],
  ['🔥', 'Fire', 'fire hot lit trending'],
  ['✨', 'Sparkles', 'sparkle magic new shine'],
  ['⭐', 'Star', 'star favourite rating'],
  ['🌟', 'Glowing star', 'star shine glow'],
  ['⚡', 'High voltage', 'lightning fast energy zap'],
  ['💥', 'Collision', 'boom bang explode'],
  ['🎯', 'Direct hit', 'target goal bullseye aim'],
  ['🚀', 'Rocket', 'launch rocket space startup'],
  ['📌', 'Pushpin', 'pin location note'],
  ['📍', 'Round pushpin', 'location map pin place'],
  ['🔔', 'Bell', 'notification alert bell'],
  ['🔒', 'Locked', 'lock secure private'],
  ['🔑', 'Key', 'key password access'],
  // celebration & objects
  ['🎉', 'Party popper', 'party celebrate tada congrats'],
  ['🎊', 'Confetti ball', 'party celebrate confetti'],
  ['🎈', 'Balloon', 'party birthday balloon'],
  ['🎁', 'Gift', 'present gift birthday christmas'],
  ['🎂', 'Birthday cake', 'birthday cake party'],
  ['🏆', 'Trophy', 'win award trophy prize champion'],
  ['🥇', 'Gold medal', 'first winner medal gold'],
  ['🎵', 'Musical note', 'music note song'],
  ['🎧', 'Headphones', 'music listen audio podcast'],
  ['🎤', 'Microphone', 'sing karaoke mic podcast'],
  ['📷', 'Camera', 'photo camera picture'],
  ['🎬', 'Clapper board', 'film movie video action'],
  ['💻', 'Laptop', 'computer laptop work tech'],
  ['📱', 'Mobile phone', 'phone mobile smartphone'],
  ['✉️', 'Envelope', 'mail email letter'],
  ['📅', 'Calendar', 'date calendar schedule event'],
  ['⏰', 'Alarm clock', 'time alarm clock'],
  ['💰', 'Money bag', 'money cash rich'],
  ['💎', 'Gem stone', 'diamond gem jewel luxury'],
  ['🛒', 'Shopping cart', 'shop cart buy sale'],
  ['📚', 'Books', 'books study read school'],
  ['✏️', 'Pencil', 'pencil write edit school'],
  ['🎨', 'Artist palette', 'art paint palette design'],
  ['🧩', 'Puzzle piece', 'puzzle piece game'],
  ['🎮', 'Video game', 'game gaming controller'],
  ['⚽', 'Football', 'soccer football sport ball'],
  ['🏀', 'Basketball', 'basketball sport ball'],
  // nature & weather
  ['☀️', 'Sun', 'sun sunny weather summer'],
  ['🌈', 'Rainbow', 'rainbow pride colour'],
  ['☁️', 'Cloud', 'cloud weather'],
  ['❄️', 'Snowflake', 'snow winter cold christmas'],
  ['🌙', 'Crescent moon', 'moon night sleep'],
  ['🌍', 'Globe', 'world earth globe travel'],
  ['🌸', 'Cherry blossom', 'flower spring blossom pink'],
  ['🌹', 'Rose', 'rose flower love red'],
  ['🌻', 'Sunflower', 'sunflower flower summer'],
  ['🌴', 'Palm tree', 'palm beach tropical summer'],
  ['🍀', 'Four leaf clover', 'luck clover green'],
  ['🍁', 'Maple leaf', 'autumn fall leaf'],
  ['🌊', 'Water wave', 'wave ocean sea beach'],
  // animals
  ['🐶', 'Dog face', 'dog puppy pet animal'],
  ['🐱', 'Cat face', 'cat kitten pet animal'],
  ['🦊', 'Fox', 'fox animal'],
  ['🐻', 'Bear', 'bear animal'],
  ['🐼', 'Panda', 'panda animal'],
  ['🦁', 'Lion', 'lion animal king'],
  ['🦄', 'Unicorn', 'unicorn magic fantasy'],
  ['🦋', 'Butterfly', 'butterfly insect spring'],
  ['🐝', 'Honeybee', 'bee insect honey'],
  // food
  ['🍕', 'Pizza', 'pizza food'],
  ['🍔', 'Hamburger', 'burger food'],
  ['🍟', 'French fries', 'fries chips food'],
  ['🌮', 'Taco', 'taco food mexican'],
  ['🍩', 'Doughnut', 'donut sweet food'],
  ['🍦', 'Ice cream', 'ice cream dessert summer'],
  ['🍓', 'Strawberry', 'strawberry fruit'],
  ['🍉', 'Watermelon', 'watermelon fruit summer'],
  ['🥑', 'Avocado', 'avocado food healthy'],
  ['☕', 'Hot beverage', 'coffee tea cafe drink'],
  ['🍷', 'Wine glass', 'wine drink'],
  ['🍾', 'Champagne', 'champagne bottle celebrate'],
  // travel
  ['✈️', 'Airplane', 'plane flight travel'],
  ['🚗', 'Car', 'car drive automobile'],
  ['🏠', 'House', 'home house property'],
  ['🏖️', 'Beach', 'beach holiday umbrella'],
  ['⛰️', 'Mountain', 'mountain hiking nature'],
];

export const EMOJI: EmojiDef[] = RAW.map(([char, name, keys]) => ({ char, name, keys }));
